version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample-get-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4984dkutk2ko"
s3_prefix = "sample-get-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
